# mutagent unified configuration (.mutagent/config.yaml)
# Generated by: pnpx @mutagent/diagnostics init
# Generated at: {{GENERATED_AT}}
# Skill version: {{SKILL_VERSION}}
#
# CONFIG SHAPE: v0.2.0 (config-shape break — see references/config-migration.md).
# ONE config drives the whole ADL lifecycle. Three top-level blocks:
#   global    — framework-wide shared resources (providers, workspace, models,
#               context links, the SOURCES + TARGETS catalogs).
#   lifecycle — per-skill behavior, keyed by skill name. Diagnostics reads
#               `lifecycle.diagnostics`.
#   triggers  — the future monitor (per stage, ships DISABLED). Absorbs the old
#               diagnostics schedule / trigger_rules / heartbeat.
#
# Full field docs: references/config-migration.md + the orchestrator's
# references/config-migration.md.

config_version: "0.2.0"

# ══ GLOBAL — framework-wide shared resources ══════════════════════════════════
global:
  # SOURCES catalog — where traces live. The diagnostics skill binds one BY ROLE
  # (source-consumer). One entry ⇒ auto-bound; more than one ⇒ disambiguate.
  sources:
    - name: primary                       # catalog id (referenced by role)
      platform: "{{SOURCE_PLATFORM}}"     # langfuse | otel | local-jsonl | claude-code | codex
      # project: my-project               # platform namespace/dataset (langfuse)
      # endpoint: "https://cloud.langfuse.com"   # self-hosted URL; omit ⇒ default CLI/env auth
      # credential_ref: LANGFUSE_SECRET_KEY      # env-var NAME (never the secret) — or {env, path}
      # paths: ["traces/*.jsonl"]         # file sources (mutually exclusive with endpoint)
      # format: langfuse-export           # normalizer hint: langfuse-export | claude-code | codex | raw
      # agent_field: agentId              # JSON field naming the agent in a record
      # latency_unit: auto                # auto | ms | s

  # TARGETS catalog — where fixes are applied. The diagnostics-apply role binds one.
  # For a report-only run you may OMIT targets entirely (see lifecycle.diagnostics.apply).
  targets:
    - name: agents                        # catalog id (referenced by role)
      platform: "{{TARGET_PLATFORM}}"     # local-claude | local-codex | ... | cloud-rest | report-only
      mode: local                         # local (worktree file edits) | remote (REST PUT)
      root: ".claude/agents/"             # root dir for local targets
      # rest_base_url: "https://api.example.com"  # remote targets
      # repo_url: "https://github.com/org/repo"   # code-pr targets (gh CLI access)
      # code_refs:                        # precise links to the agent/tooling definition files
      #   - { path: ".claude/agents/x.md", why: "the agent definition to patch" }
      # credential_ref: REST_API_TOKEN    # env-var NAME for REST auth
      apply:
        kind: markdown                    # code-pr | markdown | cloud-deploy | report-only
        # pr: true                        # open a PR vs commit directly
        # versioning: true                # version the deploy (cloud-deploy)

  # PROJECT-WIDE context links (every skill loads these at run start). Optional.
  # context:
  #   - path: docs/product-context.md
  #     what: product overview
  #     why: grounds the domain the diagnosed agent operates in
  #     when: always, at run start

# ══ LIFECYCLE — per-skill behavior (diagnostics reads its own section) ═════════
lifecycle:
  diagnostics:
    # report-only ⇒ produce the report + SKIP the apply gate (no target needed).
    # Any other value ⇒ the apply gate runs (needs a resolvable global target).
    apply: report-only

    # Stage-specific context links (the triage runbook). Loaded at run start
    # alongside global.context[]. Optional.
    # context:
    #   - path: docs/triage-runbook.md
    #     what: triage runbook
    #     why: how we classify failure modes for this project
    #     when: at diagnose start

    # Which host tool asks the operator questions (auto-detected by cli/init.ts).
    ask_tool:
      runtime: "{{ASK_RUNTIME}}"          # claude-code | codex | cursor | opencode | generic
      # native_tool: AskUserQuestion
      # fallback: chat-multi-choice

    # Audience for the rendered report when no explicit --audience flag is passed.
    #   client   — client-stripped report (internal nodes NODE-STRIPPED). DEFAULT.
    #   internal — full report (Methodology + Trajectory + internal banners).
    # NOTE: self-diagnosis reports are ALWAYS internal regardless of this (PR-022).
    default_audience: "client"

    # Default tags applied to every diagnostic run (filtering history). Optional.
    # run_tags: ["production"]

    # [INTERNAL · MAINTAINER-only] self-RCA. Clients ship disabled. On-demand only.
    self_diagnostics:
      enabled: false

# ══ TRIGGERS — the future monitor (per stage, ships DISABLED) ══════════════════
# Absorbs the old diagnostics schedule / trigger_rules / heartbeat. On-demand only.
triggers:
  diagnose:
    enabled: false
    rules: []
    # schedule:  { mode: on-demand }
    # heartbeat: { notify_on_matches: true, max_diagnostics_per_day: 3 }
