## Problem

{{PROBLEM_DESCRIPTION}}

Diagnosed from: `{{SOURCE_PLATFORM}}` traces ({{TRACE_COUNT}} analyzed).
Trigger: {{TRIGGER_DESCRIPTION}}

## Solution

{{SOLUTION_DESCRIPTION}}

Remedy type: `{{REMEDY_TYPE}}`
Target platform: `{{TARGET_PLATFORM}}`
Target class: `{{TARGET_CLASS}}`

## Key Decisions

| Decision | Choice | Rationale |
|----------|--------|-----------|
{{KEY_DECISIONS_ROWS}}

## Changes

| File | Purpose |
|------|---------|
{{CHANGES_ROWS}}

## Key Links

{{KEY_LINKS}}

## Diagnostics Evidence

| Finding ID | Severity | What | Why (root cause) | Where |
|------------|----------|------|------------------|-------|
{{FINDINGS_EVIDENCE_ROWS}}

**Full report**: {{REPORT_PATH}}

## Testing

- TDD loop passed: {{TDD_PASSED}}
- Lint: {{LINT_STATUS}}
- Typecheck: {{TYPECHECK_STATUS}}

## Shortcuts Loaded

{{SHORTCUTS_LOADED_LIST}}

## Risks & Limitations

{{RISKS_AND_LIMITATIONS}}

---
*Generated by mutagent-diagnostics v{{SKILL_VERSION}} — {{GENERATED_AT}}*
{{INTERNAL_TAG}}
